name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: com-mwallx

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=iOS Motion Wallpaper & Nugget Guide
            org.opencontainers.image.description=Breathe life into your iPhone with stunning dynamic backgrounds. Discover the best Motion Wallpapers and master the Nugget customization tool safely without jailbreak.
            org.opencontainers.image.url=https://mwallx.com/
            org.opencontainers.image.source=https://github.com/john-0x01/nugget-wallpaper
            org.opencontainers.image.documentation=https://nugget.host
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,prefix=sha-
            type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Docker Hub overview
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: "Breathe life into your iPhone with stunning Motion Wallpapers (No Jailbreak)"
          readme-filepath: ./README.md
